# Generated by Django 4.2.11 on 2026-03-12 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flujopdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('state', models.SmallIntegerField(choices=[(0, 'open'), (1, 'approved'), (2, 'rejected')], default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flujopdf.job')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
